# defaults:
#   - _self_

seed: 42

output_dir: "outputs"

data:
  augmentation: "advanced"  # none, basic, advanced
  split_method: "stratified"  # kfold, stratified_kfold
  val_size: 0.2  # stratified split에서 사용할 validation set 비율
  n_splits: 5
  fold_index: 0
  path: "data/raw"
  url: "https://aistages-api-public-prod.s3.amazonaws.com/app/Competitions/000341/data/data.tar.gz"
  balance_strategy: "augmentation"  # none, augmentation, weighted_sampler
  aug_strategy: "target"  # median, max, target
  target_count: 1000 #null  # aug_strategy가 target일 때 사용할 목표 샘플 수
  # none: 클래스 불균형 처리 없음
  # augmentation: 중간값 기준으로 소수 클래스 증강
  # weighted_sampler: 클래스별 가중치를 적용한 샘플링
  balance_classes: true
  val_selection:
    enabled: true  # validation set 추가 전략 사용 여부
    strategy: "none"  # none, random, balanced, test_similar
    similarity_metrics:  # test_similar 전략 사용시
      - "image_stats"  # 이미지 통계 기반
      - "feature_dist"  # 특징 분포 기반
      - "domain_score"  # 도메인 유사도
  
model:
 # 모델 아키텍처 선택
  # ResNet 계열:
  #   - resnet18, resnet34, resnet50, resnet101
  #   - 이미지 크기 유연함 (224, 256, 512 등)
  # EfficientNet 계열:
  #   - efficientnet_b0 (224x224)
  #   - efficientnet_b1 (240x240)
  #   - efficientnet_b2 (260x260)
  #   - efficientnet_b3 (300x300)
  #   - efficientnet_b4 (380x380)
  #   - efficientnet_b5 (456x456)
  #   - efficientnet_b6 (528x528)
  #   - efficientnet_b7 (600x600)
  # ViT 계열:
  #   - vit_base_patch16_224: 기본 ViT 모델
  #   - vit_small_patch16_224: 작은 버전
  #   - vit_large_patch16_224: 큰 버전
  #   - vit_tiny_patch16_224: 매우 작은 버전
  #   - 이미지 크기 224x224 고정
  name: "efficientnet_b0"  # 콜론 제거
  num_classes: 17
  pretrained: true  # true: pretrained weights 사용, false: random init
  init_method: "xavier_uniform"  # none, xavier_uniform, xavier_normal, kaiming_uniform, kaiming_normal
  init_params:
    gain: 1.0  # xavier init에 사용
    mode: "fan_in"  # kaiming init에 사용 (fan_in, fan_out)
    nonlinearity: "relu"  # kaiming init에 사용
  regularization:
    dropout: 0.0  # dropout 비율
    weight_decay: 0.0  # L2 regularization
    label_smoothing: 0.2  # 0.0-1.0
  domain_adaptation:
    method: "none"  # none, tta, adabn, dann
    # none: 도메인 적응 없음
    # tta: Test-Time Augmentation
    # adabn: Adaptive Batch Normalization
    # dann: Domain Adversarial Neural Network
    tta_steps: 100  # tta 적용 시 반복 횟수
    tta_lr: 0.0001  # tta 적용 시 learning rate

train:
  epochs: 1
  batch_size: 32
  img_size: 224
  lr: 1e-3
  num_workers: 0
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.001
  mixed_precision:
    enabled: true

logger:
  use_wandb: true
  save_interval: none
  entity: "ailab_upstage_fastcampus"
  project_name: "test"
  reinit: true
  metrics:
    epoch: ["loss", "accuracy", "f1"]
    global: ["epoch", "learning_rate"]
    class_metrics: ["f1"]