# defaults:
#   - _self_

data:
  augmentation: "basic"
  split_method: "holdout"
  path: "data"

model:
  name: "resnet34"
  num_classes: 17
  pretrained: true
  class_balancing:
    method: "none"
  domain_adaptation:
    method: "none"

train:
  epochs: 1
  batch_size: 32
  img_size: 32
  lr: 1e-3
  num_workers: 0
  early_stopping:
    enabled: false
  mixed_precision:
    enabled: false

logger:
  use_wandb: true
  entity: "ailab_upstage_fastcampus"
  project_name: "test_val"
  metrics:
    train: ["loss", "accuracy", "f1"]
    val: ["loss", "accuracy", "f1"]
    global: ["epoch", "learning_rate"]
    class_metrics: ["f1"]