# defaults:
#   - _self_

seed: 42

output_dir: "outputs"

data:
  augmentation: "advanced"
  split_method: "stratified_kfold"
  val_size: 0.2  # validation 사용
  path: "data/raw"
  url: "https://aistages-api-public-prod.s3.amazonaws.com/app/Competitions/000341/data/data.tar.gz"
  balance_classes: true  # class imbalance 보정 옵션 추가
  
model:
  name: "resnet34"
  num_classes: 17
  pretrained: true
  domain_adaptation:
    method: "adabn" #"tta"
    tta_steps: 100
    tta_lr: 0.0001

train:
  epochs: 50
  batch_size: 32
  img_size: 32
  lr: 1e-3
  num_workers: 0
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.001
  mixed_precision:
    enabled: true

logger:
  use_wandb: true
  entity: "ailab_upstage_fastcampus"
  project_name: "ailab_contest_cv_team_1"
  metrics:
    train: ["loss", "accuracy", "f1"]
    val: ["loss", "accuracy", "f1"]
    global: ["epoch", "learning_rate"]
    class_metrics: ["f1"]